# Generated by Django 4.2 on 2023-04-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapphire', '0002_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='ctrl_num',
            field=models.CharField(max_length=255),
        ),
    ]
