# Generated by Django 4.2 on 2023-04-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapphire', '0003_rename_otp_user_email_otp_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
