# Generated by Django 4.2 on 2023-04-07 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sapphire', '0006_user_temporary_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='temporary_password',
        ),
    ]
