# Generated by Django 4.2 on 2023-04-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapphire', '0008_user_show_modal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
