# Generated by Django 4.2 on 2023-04-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sapphire', '0011_alter_user_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='show_modal',
            field=models.BooleanField(default=True),
        ),
    ]
